flowchart LR
    n0["MultimodalAgent<br/>359,188 parameters<br/>initial [30, 32]"]
    n1["encoders: ModuleDict<br/>225,216 parameters"]
    n2["image: MultiScaleImageEncoder<br/>54,976 parameters"]
    n3["video: MultiScaleImageEncoder<br/>54,976 parameters"]
    n4["audio: MultiScaleAudioEncoder<br/>53,568 parameters"]
    n5["text: MultiScaleTextEncoder<br/>61,696 parameters"]
    n6["decoders: ModuleDict<br/>57,619 parameters"]
    n7["image: ImageDecoder<br/>10,704 parameters"]
    n8["audio: AudioDecoder<br/>12,864 parameters"]
    n9["text: TextDecoder<br/>34,051 parameters"]
    n10["updater: ObservationUpdate<br/>9,792 parameters"]
    n11["action: Linear<br/>128 parameters"]
    n12["blocks: ModuleList<br/>8,608 parameters"]
    n13["scale: Linear<br/>1,056 parameters"]
    n14["dynamics: LatentDynamics<br/>20,512 parameters"]
    n15["action: Linear<br/>128 parameters"]
    n16["uncertainty: Linear<br/>1,056 parameters"]
    n17["blocks: ModuleList<br/>17,216 parameters"]
    n18["delta: Linear<br/>1,056 parameters"]
    n19["scale: Linear<br/>1,056 parameters"]
    n20["thinker: Thinker<br/>9,792 parameters"]
    n21["read: Attend<br/>8,608 parameters"]
    n22["feedback: Sequential<br/>1,184 parameters"]
    n23["memory: EpisodicMemory<br/>0 parameters"]
    n24["action_head: ActionHead<br/>132 parameters"]
    n25["output: Linear<br/>132 parameters"]
    n26["monitor: ErrorMonitor<br/>1,089 parameters"]
    n27["output: Sequential<br/>1,089 parameters"]
    n28["feature_controller: FeatureController<br/>592 parameters"]
    n29["output: Sequential<br/>592 parameters"]
    n30["task_interpreter: TaskInterpreter<br/>17,344 parameters"]
    n31["read_instruction: Attend<br/>8,608 parameters"]
    n32["read_state: Attend<br/>8,608 parameters"]
    n33["task_policy: TaskPolicy<br/>1,516 parameters"]
    n34["process: Sequential<br/>1,120 parameters"]
    n35["operation: Linear<br/>231 parameters"]
    n36["modality: Linear<br/>132 parameters"]
    n37["completion: Linear<br/>33 parameters"]
    n38["metadata_encoder: MetadataEncoder<br/>14,624 parameters"]
    n39["embedding: Embedding<br/>8,288 parameters"]
    n40["sequence: GRU<br/>6,336 parameters"]
    n0 -.-> n1
    n1 -.-> n2
    n1 -.-> n3
    n1 -.-> n4
    n1 -.-> n5
    n0 -.-> n6
    n6 -.-> n7
    n6 -.-> n8
    n6 -.-> n9
    n0 -.-> n10
    n10 -.-> n11
    n10 -.-> n12
    n10 -.-> n13
    n0 -.-> n14
    n14 -.-> n15
    n14 -.-> n16
    n14 -.-> n17
    n14 -.-> n18
    n14 -.-> n19
    n0 -.-> n20
    n20 -.-> n21
    n20 -.-> n22
    n0 -.-> n23
    n0 -.-> n24
    n24 -.-> n25
    n0 -.-> n26
    n26 -.-> n27
    n0 -.-> n28
    n28 -.-> n29
    n0 -.-> n30
    n30 -.-> n31
    n30 -.-> n32
    n0 -.-> n33
    n33 -.-> n34
    n33 -.-> n35
    n33 -.-> n36
    n33 -.-> n37
    n0 -.-> n38
    n38 -.-> n39
    n38 -.-> n40
