"""Build the PATH-WM experiment dashboard from completed run ledgers.

What: discover every completed ``runs/<spec>/<seed>/`` directory, reconcile its duplicated result
records, and package one offline HTML dashboard plus its canonical data artifact.
How: raw JSON/YAML/JSONL remains authoritative; this module only reshapes bounded, reviewed rows and
delegates HTML rendering and browser QA to the Data Analytics portable-artifact builder.
Why: the instrument panel is useful only when run outcomes, controls, and training trajectories can be
compared without manually reading result files (PATH-WM v0.3 §14-§15; roadmap phase 1 viewer v0).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterable

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUNS_ROOT = ROOT / "runs"
DEFAULT_ARTIFACT = DEFAULT_RUNS_ROOT / "experiment_dashboard.artifact.json"
DEFAULT_HTML = DEFAULT_RUNS_ROOT / "experiment_dashboard.html"
SOURCE_ID = "path_wm_run_ledger"
SOURCE_QUERY_PATH = "viewer/experiment_results.sql"
MAX_DATASET_ROWS = 2_000

METRIC_LABELS = {
    "action_sensitivity_ratio": "Action sensitivity",
    "counterfactual_accuracy": "Counterfactual accuracy",
    "counterfactual_branches": "Counterfactual branches",
    "counterfactual_probe_count": "Counterfactual probe groups",
    "probe_count": "Probe trajectories",
    "probe_horizon": "Probe horizon",
    "transition_error": "Endpoint transition error",
    "transition_error_identity": "Identity error",
    "transition_error_one_step": "Correct-action error",
    "transition_error_shuffled_action": "Shuffled-action error",
    "transition_error_zero_action": "Zero-action error",
}

METRIC_DEFINITIONS = {
    "Action sensitivity": (
        "Mean norm of the predictor-output difference under opposite valid actions, divided by the "
        "norm of the current ABI state, over the fixed probe set."
    ),
    "Counterfactual accuracy": (
        "Share of fixed paired-intervention branch predictions whose nearest target is the branch "
        "generated by the matching action; chance is 1/K."
    ),
    "Correct-action error": (
        "One-step fp32 mean-squared latent error using the recorded action over every fixed-probe "
        "trajectory transition. Lower is better only relative to the matched controls."
    ),
    "Endpoint transition error": (
        "Free-running fp32 mean-squared latent error at the configured fixed-probe horizon endpoint."
    ),
    "Identity error": "One-step latent MSE when the current state itself is used as the prediction.",
    "Zero-action error": "One-step latent MSE when the predictor receives a zero action.",
    "Shuffled-action error": (
        "One-step latent MSE when actions are deterministically rotated across probe trajectories "
        "at the same time index."
    ),
}

CONTEXT_METRICS = {
    "counterfactual_branches",
    "counterfactual_probe_count",
    "probe_count",
    "probe_horizon",
}
CONTROL_METRICS = [
    ("transition_error_identity", "Identity control ↑"),
    ("transition_error_one_step", "Correct action ↓"),
    ("transition_error_zero_action", "Zero-action control ↑"),
    ("transition_error_shuffled_action", "Shuffled-action control ↑"),
]
TRANSITION_METRICS = [
    ("transition_error_one_step", "One step"),
    ("transition_error", "H-step endpoint"),
]
TRAINING_PRIMARY_OBJECTIVES = ["total", "action", "rollout", "inverse"]
TRAINING_AUXILIARY_OBJECTIVES = ["counterfactual", "reg", "chunk"]
TRAINING_OBJECTIVES = TRAINING_PRIMARY_OBJECTIVES + TRAINING_AUXILIARY_OBJECTIVES
RUN_CARD_PRIORITY = [
    "action_sensitivity_ratio",
    "counterfactual_accuracy",
    "transition_error_one_step",
    "transition_error",
]
CARD_FIELD_OVERRIDES = {
    "action_sensitivity_ratio": ("action_sensitivity_milli", "Action sensitivity (×10⁻³)"),
    "transition_error_one_step": ("transition_error_one_step_milli", "Correct-action MSE (×10⁻³)"),
    "transition_error": ("transition_error_milli", "Endpoint MSE (×10⁻³)"),
}
DIRECTION_HINTS = {
    "higher": "↑ higher is better",
    "lower": "↓ lower is better",
    "relative": "↓ correct / ↑ controls",
    "context": "↔ context only",
}
METRIC_DIRECTIONS = {
    "action_sensitivity_ratio": "higher",
    "counterfactual_accuracy": "higher",
    "transition_error": "lower",
    "transition_error_identity": "lower",
    "transition_error_one_step": "lower",
    "transition_error_shuffled_action": "lower",
    "transition_error_zero_action": "lower",
}


class DashboardDataError(RuntimeError):
    """The ledger disagrees with itself, so a trustworthy dashboard cannot be built."""


class DashboardBuildError(RuntimeError):
    """The canonical artifact could not be packaged as portable HTML."""


@dataclass(frozen=True)
class RunResult:
    """One reconciled, completed experiment seed."""

    run_id: str
    label: str
    run_dir: Path
    source_paths: tuple[str, ...]
    completed_at: datetime
    status: str
    experiment: str
    seed: int
    step: int
    device: str
    metrics: dict[str, int | float]
    parameter_counts: dict[str, int | float]
    final_training: dict[str, int | float]
    training: tuple[dict[str, int | float], ...]
    thresholds: dict[str, Any]
    spec: dict[str, Any]


def _read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise DashboardDataError(f"cannot read {path}: {error}") from error
    if not isinstance(value, dict):
        raise DashboardDataError(f"{path} must contain a JSON object")
    return value


def _read_jsonl(path: Path) -> tuple[dict[str, int | float], ...]:
    rows: list[dict[str, int | float]] = []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise DashboardDataError(f"cannot read {path}: {error}") from error
    for line_number, line in enumerate(lines, start=1):
        if not line.strip():
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError as error:
            raise DashboardDataError(f"cannot read {path}:{line_number}: {error}") from error
        if not isinstance(value, dict):
            raise DashboardDataError(f"{path}:{line_number} must contain a JSON object")
        row = {key: item for key, item in value.items() if _is_number(item)}
        _validate_finite(row, f"{path}:{line_number}")
        rows.append(row)
    return tuple(rows)


def _read_yaml(path: Path) -> dict[str, Any]:
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as error:
        raise DashboardDataError(f"cannot read {path}: {error}") from error
    if not isinstance(value, dict):
        raise DashboardDataError(f"{path} must contain a YAML mapping")
    return value


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _numeric_mapping(value: Any, path: str) -> dict[str, int | float]:
    if not isinstance(value, dict):
        raise DashboardDataError(f"{path} must be an object")
    output = {str(key): item for key, item in value.items() if _is_number(item)}
    _validate_finite(output, path)
    return output


def _validate_finite(values: dict[str, int | float], path: str) -> None:
    invalid = [key for key, value in values.items() if not math.isfinite(float(value))]
    if invalid:
        raise DashboardDataError(f"{path} contains non-finite numeric values: {', '.join(invalid)}")


def _path_label(relative_run_dir: Path, seed: int) -> str:
    parts = relative_run_dir.parts
    development = parts[:1] == ("dev",)
    variant_parts = parts[1:-1] if development else parts[:-1]
    variant = " / ".join(part.replace("_", " ") for part in variant_parts) or "run"
    prefix = "DEV · " if development else ""
    return f"{prefix}{variant} · seed {seed}"


def _relative_source(path: Path, project_root: Path) -> str:
    try:
        return path.resolve().relative_to(project_root.resolve()).as_posix()
    except ValueError as error:
        raise DashboardDataError(f"run artifact is outside the project root: {path}") from error


def collect_run_results(runs_root: Path = DEFAULT_RUNS_ROOT) -> tuple[list[RunResult], list[str]]:
    """Return completed runs plus non-fatal notices for incomplete run directories."""

    runs_root = runs_root.resolve()
    project_root = runs_root.parent
    if not runs_root.exists():
        return [], [f"Run root does not exist yet: {runs_root}"]

    candidate_dirs = {
        path.parent for pattern in ("metrics.json", "run_summary.json") for path in runs_root.rglob(pattern)
    }
    results: list[RunResult] = []
    notices: list[str] = []
    for run_dir in sorted(candidate_dirs):
        metrics_path = run_dir / "metrics.json"
        summary_path = run_dir / "run_summary.json"
        spec_path = run_dir / "spec.yaml"
        training_path = run_dir / "training.jsonl"
        missing = [path.name for path in (metrics_path, summary_path, spec_path) if not path.is_file()]
        if missing:
            relative = run_dir.relative_to(runs_root).as_posix()
            notices.append(f"Skipped incomplete run {relative}: missing {', '.join(missing)}")
            continue

        metrics_record = _read_json(metrics_path)
        summary = _read_json(summary_path)
        spec = _read_yaml(spec_path)
        metrics = _numeric_mapping(metrics_record.get("metrics"), f"{metrics_path}:metrics")
        summary_metrics = _numeric_mapping(summary.get("metrics"), f"{summary_path}:metrics")
        if metrics != summary_metrics:
            raise DashboardDataError(
                f"metric copies disagree for {run_dir}; metrics.json is the evaluation source of truth"
            )

        final_training = _numeric_mapping(summary.get("final_training", {}), f"{summary_path}:final_training")
        training = _read_jsonl(training_path) if training_path.is_file() else ()
        if training and final_training != training[-1]:
            raise DashboardDataError(f"final_training disagrees with the last training row for {run_dir}")
        if not training:
            notices.append(f"Run {run_dir.relative_to(runs_root).as_posix()} has no training trajectory")

        threshold_path = run_dir / "threshold_record.json"
        threshold_record = _read_json(threshold_path) if threshold_path.is_file() else {}
        threshold_metrics = threshold_record.get("metrics")
        if isinstance(threshold_metrics, dict):
            comparable = _numeric_mapping(threshold_metrics, f"{threshold_path}:metrics")
            if comparable != metrics:
                notices.append(
                    f"Threshold record is stale for {run_dir.relative_to(runs_root).as_posix()}; "
                    "evaluation metrics control the dashboard"
                )

        relative_run_dir = run_dir.relative_to(runs_root)
        seed = int(metrics_record.get("seed", relative_run_dir.name))
        step = int(metrics_record.get("step", final_training.get("step", 0)))
        status = str(metrics_record.get("status", spec.get("status", "unknown")))
        source_files = [metrics_path, summary_path, spec_path]
        if training_path.is_file():
            source_files.append(training_path)
        if threshold_path.is_file():
            source_files.append(threshold_path)
        completed_at = datetime.fromtimestamp(
            max(path.stat().st_mtime for path in source_files),
            tz=UTC,
        )
        parameter_counts = _numeric_mapping(
            metrics_record.get("parameter_counts", {}),
            f"{metrics_path}:parameter_counts",
        )
        results.append(
            RunResult(
                run_id=relative_run_dir.as_posix(),
                label=_path_label(relative_run_dir, seed),
                run_dir=run_dir,
                source_paths=tuple(_relative_source(path, project_root) for path in source_files),
                completed_at=completed_at,
                status=status,
                experiment=str(spec.get("experiment", "unknown")),
                seed=seed,
                step=step,
                device=str(summary.get("device", "unknown")),
                metrics=metrics,
                parameter_counts=parameter_counts,
                final_training=final_training,
                training=training,
                thresholds=(
                    threshold_record.get("thresholds", {})
                    if isinstance(threshold_record.get("thresholds"), dict)
                    else {}
                ),
                spec=spec,
            )
        )
    results.sort(key=lambda run: (run.completed_at, run.run_id))
    return results, notices


def _nested(mapping: dict[str, Any], *keys: str, default: Any = None) -> Any:
    value: Any = mapping
    for key in keys:
        if not isinstance(value, dict) or key not in value:
            return default
        value = value[key]
    return value


def _metric_label(name: str) -> str:
    return METRIC_LABELS.get(name, name.replace("_", " ").strip().title())


def _metric_format(name: str) -> str:
    if name == "counterfactual_accuracy" or name.endswith(("_accuracy", "_rate", "_share")):
        return "percent"
    return "number"


def _metric_direction(name: str) -> str:
    """Return only defensible optimization direction; unknown measures stay contextual."""

    if name in METRIC_DIRECTIONS:
        return METRIC_DIRECTIONS[name]
    normalized = name.lower()
    if any(token in normalized for token in ("accuracy", "success", "throughput", "recall")):
        return "higher"
    if any(token in normalized for token in ("error", "loss", "latency", "regret")):
        return "lower"
    return "context"


def _exact_value(value: Any) -> str:
    if value is None:
        return "Not set"
    if isinstance(value, float):
        return f"={format(value, '.12g')}"
    if isinstance(value, int) and not isinstance(value, bool):
        return f"={value}"
    return str(value)


def _downsample(rows: tuple[dict[str, int | float], ...], limit: int) -> list[dict[str, int | float]]:
    if limit <= 0 or len(rows) <= limit:
        return [dict(row) for row in rows]
    if limit == 1:
        return [dict(rows[-1])]
    indices = {round(index * (len(rows) - 1) / (limit - 1)) for index in range(limit)}
    return [dict(rows[index]) for index in sorted(indices)]


def _source(run_results: list[RunResult], generated_at: str) -> dict[str, Any]:
    source_sql = (ROOT / SOURCE_QUERY_PATH).read_text(encoding="utf-8")
    return {
        "id": SOURCE_ID,
        "label": "PATH-WM completed run ledger",
        "path": SOURCE_QUERY_PATH,
        "query": {
            "engine": "duckdb",
            "language": "sql",
            "sql": source_sql,
            "description": (
                "The dashboard generator reconciled metrics.json, run_summary.json, training.jsonl, "
                "threshold_record.json, and copied spec.yaml files for every completed run. The "
                "attached DuckDB views reproduce direct access to the JSON and JSONL evidence."
            ),
            "executed_at": generated_at,
            "tables_used": [
                "runs/**/metrics.json",
                "runs/**/run_summary.json",
                "runs/**/training.jsonl",
                "runs/**/threshold_record.json",
                "runs/**/spec.yaml",
            ],
            "reviewed_file_count": len({path for run in run_results for path in run.source_paths}),
            "filters": ["completed runs with matching metrics.json and run_summary.json metric copies"],
            "metric_definitions": METRIC_DEFINITIONS,
        },
    }


def _chart(
    chart_id: str,
    title: str,
    subtitle: str,
    dataset: str,
    chart_type: str,
    x: dict[str, Any],
    y: dict[str, Any],
    *,
    color: dict[str, Any] | None = None,
    layout: str = "half",
    tooltip: list[dict[str, Any]] | None = None,
    reference_lines: list[dict[str, Any]] | None = None,
    group_mode: str | None = None,
    orientation: str | None = None,
    direction: str | None = None,
) -> dict[str, Any]:
    encodings: dict[str, Any] = {"x": x, "y": y}
    if color is not None:
        encodings["color"] = color
    if tooltip:
        encodings["tooltip"] = tooltip
    if direction is not None:
        title = f"{title} · {DIRECTION_HINTS[direction]}"
    chart: dict[str, Any] = {
        "id": chart_id,
        "title": title,
        "subtitle": subtitle,
        "intent": "trend" if chart_type == "line" else "comparison",
        "type": chart_type,
        "dataset": dataset,
        "sourceId": SOURCE_ID,
        "encodings": encodings,
        "layout": layout,
        "palette": {"kind": "categorical" if color else "identity", "name": "PATH-WM blue-orange"},
        "labels": {"values": "auto" if chart_type == "bar" else "endpoints"},
        "surface": {"interactiveLegend": color is not None, "viewMode": "both"},
    }
    if color is not None:
        chart["legend"] = {"position": "bottom", "sort": "spec"}
    if reference_lines:
        chart["referenceLines"] = reference_lines
    if chart_type == "line":
        settings: dict[str, Any] = {"showPoints": "never"}
    else:
        settings = {"showValues": True, "sort": "none"}
        if group_mode:
            settings["groupMode"] = group_mode
        if orientation:
            settings.update({"orientation": orientation, "categoryLabelPolicy": "wrap"})
    chart["settings"] = settings
    return chart


def build_dashboard_artifact(
    run_results: list[RunResult],
    notices: Iterable[str] = (),
) -> dict[str, Any]:
    """Shape reconciled results into the canonical Data Analytics dashboard contract."""

    if not run_results:
        raise DashboardDataError("no completed experiment runs were found")
    latest = run_results[-1]
    generated_at = latest.completed_at.isoformat().replace("+00:00", "Z")
    notices = list(notices)
    metric_names = sorted({name for run in run_results for name in run.metrics})
    training_fields = sorted({name for run in run_results for row in run.training for name in row})

    overview_rows: list[dict[str, Any]] = []
    run_inventory: list[dict[str, Any]] = []
    result_detail: list[dict[str, Any]] = []
    action_controls: list[dict[str, Any]] = []
    transitions: list[dict[str, Any]] = []
    sensitivity: list[dict[str, Any]] = []
    counterfactual_evaluation: list[dict[str, Any]] = []
    parameter_counts: list[dict[str, Any]] = []

    for run in run_results:
        counterfactual_weight = _nested(run.spec, "losses", "counterfactual", "weight")
        kappa = _nested(run.spec, "losses", "counterfactual", "kappa")
        overview = {
            "run": run.label,
            "run_id": run.run_id,
            "experiment": run.experiment,
            "status": run.status,
            "seed": run.seed,
            "step": run.step,
            "device": run.device,
            "completed_at": run.completed_at.isoformat().replace("+00:00", "Z"),
            **{name: run.metrics.get(name) for name in metric_names},
        }
        for source_field, (scaled_field, _) in CARD_FIELD_OVERRIDES.items():
            value = run.metrics.get(source_field)
            overview[scaled_field] = value * 1_000 if value is not None else None
        overview_rows.append(overview)
        run_inventory.append(
            {
                "run": run.label,
                "status": run.status,
                "experiment": run.experiment,
                "seed": run.seed,
                "step": run.step,
                "device": run.device,
                "inverse": _nested(run.spec, "inverse_dynamics", "kind", default="—"),
                "counterfactual_weight": counterfactual_weight,
                "counterfactual_weight_display": _exact_value(counterfactual_weight),
                "kappa": kappa,
                "kappa_display": _exact_value(kappa),
                "train_steps": _nested(run.spec, "train", "steps"),
                "probe_count": run.metrics.get("probe_count"),
                "probe_horizon": run.metrics.get("probe_horizon"),
                "source": run.source_paths[0],
            }
        )
        for name, value in run.metrics.items():
            result_detail.append(
                {
                    "run": run.label,
                    "section": "Evaluation",
                    "metric": _metric_label(name),
                    "value": _exact_value(value),
                }
            )
        for name, value in run.final_training.items():
            result_detail.append(
                {
                    "run": run.label,
                    "section": "Final training",
                    "metric": _metric_label(name),
                    "value": _exact_value(value),
                }
            )
        for name, value in run.parameter_counts.items():
            result_detail.append(
                {
                    "run": run.label,
                    "section": "Parameters",
                    "metric": _metric_label(name),
                    "value": _exact_value(value),
                }
            )
            parameter_counts.append(
                {
                    "run": run.label,
                    "component": _metric_label(name),
                    "parameters": value,
                    "status": run.status,
                }
            )
        for name, value in run.thresholds.items():
            result_detail.append(
                {
                    "run": run.label,
                    "section": "Threshold",
                    "metric": _metric_label(name),
                    "value": _exact_value(value),
                }
            )
        for name, label in CONTROL_METRICS:
            value = run.metrics.get(name)
            if value is not None:
                action_controls.append(
                    {
                        "run": run.label,
                        "control": label,
                        "error_milli": value * 1_000,
                        "error": value,
                        "probe_count": run.metrics.get("probe_count"),
                        "probe_horizon": run.metrics.get("probe_horizon"),
                        "status": run.status,
                    }
                )
        for name, label in TRANSITION_METRICS:
            value = run.metrics.get(name)
            if value is not None:
                transitions.append(
                    {
                        "run": run.label,
                        "horizon": label,
                        "error_milli": value * 1_000,
                        "error": value,
                        "probe_count": run.metrics.get("probe_count"),
                        "probe_horizon": run.metrics.get("probe_horizon"),
                        "status": run.status,
                    }
                )
        if "action_sensitivity_ratio" in run.metrics:
            sensitivity.append(
                {
                    "run": run.label,
                    "ratio_milli": run.metrics["action_sensitivity_ratio"] * 1_000,
                    "ratio": run.metrics["action_sensitivity_ratio"],
                    "probe_count": run.metrics.get("probe_count"),
                    "status": run.status,
                }
            )
        if "counterfactual_accuracy" in run.metrics:
            branches = run.metrics.get("counterfactual_branches")
            chance = 1.0 / float(branches) if branches else None
            counterfactual_evaluation.append(
                {
                    "run": run.label,
                    "series": "Observed",
                    "accuracy": run.metrics["counterfactual_accuracy"],
                    "branches": branches,
                    "probe_groups": run.metrics.get("counterfactual_probe_count"),
                    "status": run.status,
                }
            )
            if chance is not None:
                counterfactual_evaluation.append(
                    {
                        "run": run.label,
                        "series": "Chance",
                        "accuracy": chance,
                        "branches": branches,
                        "probe_groups": run.metrics.get("counterfactual_probe_count"),
                        "status": run.status,
                    }
                )

    # Allocate a bounded number of evenly spaced training points to every completed run. The raw JSONL
    # remains the exact source; the dashboard trajectory is deliberately a compact visual extract.
    objective_count = max(1, len(TRAINING_OBJECTIVES))
    point_limit = max(2, min(50, MAX_DATASET_ROWS // max(1, len(run_results) * objective_count)))
    primary_objective_rows: list[dict[str, Any]] = []
    auxiliary_objective_rows: list[dict[str, Any]] = []
    accuracy_rows: list[dict[str, Any]] = []
    gradient_rows: list[dict[str, Any]] = []
    curriculum_rows: list[dict[str, Any]] = []
    training_detail: list[dict[str, Any]] = []
    detail_limit = max(2, min(100, MAX_DATASET_ROWS // max(1, len(run_results))))
    for run in run_results:
        for row in _downsample(run.training, point_limit):
            step = row.get("step")
            for field in TRAINING_OBJECTIVES:
                value = row.get(field)
                if value is not None and value >= 0:
                    target = (
                        primary_objective_rows
                        if field in TRAINING_PRIMARY_OBJECTIVES
                        else auxiliary_objective_rows
                    )
                    target.append(
                        {"run": run.label, "step": step, "objective": _metric_label(field), "value": value}
                    )
            gradient = row.get("gradient_norm")
            if gradient is not None:
                gradient_rows.append({"run": run.label, "step": step, "gradient_norm": gradient})
            accuracy = row.get("counterfactual_accuracy")
            if accuracy is not None and accuracy >= 0:
                branches = run.metrics.get("counterfactual_branches")
                accuracy_rows.append(
                    {"run": run.label, "step": step, "series": "Observed", "accuracy": accuracy}
                )
                if branches:
                    accuracy_rows.append(
                        {"run": run.label, "step": step, "series": "Chance", "accuracy": 1.0 / branches}
                    )
            for field in ("horizon", "delta_t"):
                value = row.get(field)
                if value is not None and value >= 0:
                    curriculum_rows.append(
                        {"run": run.label, "step": step, "signal": _metric_label(field), "value": value}
                    )
        for row in _downsample(run.training, detail_limit):
            training_detail.append(
                {
                    "run": run.label,
                    **{
                        key: value if key in {"step", "horizon", "delta_t"} else _exact_value(value)
                        for key, value in row.items()
                    },
                }
            )

    unique_variants = {run.run_id.rsplit("/", 1)[0] for run in run_results}
    summary_rows = [
        {
            "completed_runs": len(run_results),
            "variants": len(unique_variants),
            "evaluation_metrics": len(metric_names),
            "training_snapshots": sum(len(run.training) for run in run_results),
        }
    ]
    datasets: dict[str, list[dict[str, Any]]] = {
        "summary": summary_rows,
        # Put the latest completed run first so the semantic/no-script card fallback agrees with the
        # enhanced reader's default selection even though partial dashboard filters are interactive-only.
        "run_overview": list(reversed(overview_rows)),
        "run_inventory": run_inventory,
        "result_detail": result_detail[:MAX_DATASET_ROWS],
        "action_controls": action_controls,
        "transition_comparison": transitions,
        "action_sensitivity": sensitivity,
        "counterfactual_evaluation": counterfactual_evaluation,
        "parameter_counts": parameter_counts,
        "training_primary_objectives": primary_objective_rows[:MAX_DATASET_ROWS],
        "training_auxiliary_objectives": auxiliary_objective_rows[:MAX_DATASET_ROWS],
        "training_accuracy": accuracy_rows[:MAX_DATASET_ROWS],
        "training_gradient": gradient_rows[:MAX_DATASET_ROWS],
        "curriculum": curriculum_rows[:MAX_DATASET_ROWS],
        "training_detail": training_detail[:MAX_DATASET_ROWS],
    }

    cards: list[dict[str, Any]] = [
        {
            "id": "completed_runs",
            "description": "Completed seed directories whose duplicated evaluation records reconcile.",
            "dataset": "summary",
            "sourceId": SOURCE_ID,
            "metrics": [{"label": "Completed runs", "field": "completed_runs", "format": "number"}],
        },
        {
            "id": "variants",
            "description": "Distinct experiment or development-spec paths represented in this snapshot.",
            "dataset": "summary",
            "sourceId": SOURCE_ID,
            "metrics": [{"label": "Variants", "field": "variants", "format": "number"}],
        },
        {
            "id": "evaluation_metrics",
            "description": "Union of evaluation fields emitted by the completed runs.",
            "dataset": "summary",
            "sourceId": SOURCE_ID,
            "metrics": [
                {"label": "Evaluation metrics", "field": "evaluation_metrics", "format": "number"}
            ],
        },
        {
            "id": "training_snapshots",
            "description": "Logged optimization checkpoints across all completed training trajectories.",
            "dataset": "summary",
            "sourceId": SOURCE_ID,
            "metrics": [
                {"label": "Training snapshots", "field": "training_snapshots", "format": "number"}
            ],
        },
    ]
    selected_card_ids: list[str] = []
    card_metrics = [name for name in RUN_CARD_PRIORITY if name in metric_names]
    if not card_metrics:
        card_metrics = [name for name in metric_names if name not in CONTEXT_METRICS][:4]
    for name in card_metrics:
        card_id = f"selected_{name}"
        field, label = CARD_FIELD_OVERRIDES.get(name, (name, _metric_label(name)))
        direction = _metric_direction(name)
        if direction in {"higher", "lower"}:
            label = f"{label} {DIRECTION_HINTS[direction][0]}"
        selected_card_ids.append(card_id)
        cards.append(
            {
                "id": card_id,
                "description": METRIC_DEFINITIONS.get(_metric_label(name), f"Evaluation field: {name}."),
                "dataset": "run_overview",
                "sourceId": SOURCE_ID,
                "metrics": [{"label": label, "field": field, "format": _metric_format(name)}],
            }
        )

    charts: list[dict[str, Any]] = []
    blocks: list[dict[str, Any]] = [
        {
            "id": "intro",
            "type": "markdown",
            "body": (
                "## How to read this\n\nUse the run selector for one seed's cards, controls, and training "
                "trajectory. Cross-run charts remain fixed so interventions stay comparable. Raw run files "
                "remain the authoritative ledger; this page is a read-only view.\n\n"
                "**Direction key:** ↑ higher is better · ↓ lower is better · ↔ context only. In the "
                "action-control chart, correct-action error should be lower while deliberately wrong controls "
                "should remain higher relative to it."
            ),
        },
        {"id": "scope_metrics", "type": "metric-strip", "cardIds": [card["id"] for card in cards[:4]]},
    ]
    if selected_card_ids:
        blocks.extend(
            [
                {
                    "id": "selected_heading",
                    "type": "markdown",
                    "body": "## Selected run outcomes\n\nHeadline metrics for the run chosen above.",
                },
                {"id": "selected_metrics", "type": "metric-strip", "cardIds": selected_card_ids},
            ]
        )

    def add_chart(chart: dict[str, Any]) -> None:
        charts.append(chart)
        blocks.append(
            {"id": f"block_{chart['id']}", "type": "chart", "chartId": chart["id"], "layout": chart["layout"]}
        )

    if sensitivity:
        add_chart(
            _chart(
                "action_sensitivity_comparison",
                "Action sensitivity across runs",
                "Opposite-action predictor separation relative to the ABI-state norm on fixed probes.",
                "action_sensitivity",
                "bar",
                {"field": "run", "type": "nominal", "label": "Run"},
                {
                    "field": "ratio_milli",
                    "type": "quantitative",
                    "label": "Sensitivity ratio (×10⁻³)",
                    "format": "number",
                },
                tooltip=[
                    {"field": "probe_count", "type": "quantitative", "label": "Probe trajectories"},
                    {"field": "status", "type": "nominal", "label": "Status"},
                ],
                orientation="horizontal",
                direction="higher",
            )
        )
    if counterfactual_evaluation:
        add_chart(
            _chart(
                "counterfactual_accuracy_comparison",
                "Counterfactual discrimination across runs",
                "Observed fixed-probe branch accuracy is shown beside each run's 1/K chance level.",
                "counterfactual_evaluation",
                "bar",
                {"field": "run", "type": "nominal", "label": "Run"},
                {"field": "accuracy", "type": "quantitative", "label": "Accuracy", "format": "percent"},
                color={"field": "series", "type": "nominal", "label": "Series"},
                tooltip=[
                    {"field": "branches", "type": "quantitative", "label": "Branches (K)"},
                    {"field": "probe_groups", "type": "quantitative", "label": "Probe groups"},
                ],
                group_mode="grouped",
                orientation="horizontal",
                direction="higher",
            )
        )
    if transitions:
        add_chart(
            _chart(
                "transition_error_comparison",
                "Transition error across runs",
                "One-step and free-running endpoint MSE use the same fixed-probe population per run.",
                "transition_comparison",
                "bar",
                {"field": "run", "type": "nominal", "label": "Run"},
                {
                    "field": "error_milli",
                    "type": "quantitative",
                    "label": "Latent MSE (×10⁻³)",
                    "format": "number",
                },
                color={"field": "horizon", "type": "nominal", "label": "Evaluation horizon"},
                tooltip=[
                    {"field": "probe_count", "type": "quantitative", "label": "Probe trajectories"},
                    {"field": "probe_horizon", "type": "quantitative", "label": "Endpoint horizon"},
                ],
                layout="full",
                group_mode="grouped",
                orientation="horizontal",
                direction="lower",
            )
        )
    if action_controls:
        add_chart(
            _chart(
                "selected_action_controls",
                "Action-correctness controls",
                "The run selector isolates one seed; the fallback table labels all runs explicitly.",
                "action_controls",
                "bar",
                {"field": "control", "type": "nominal", "label": "Prediction input"},
                {
                    "field": "error_milli",
                    "type": "quantitative",
                    "label": "One-step latent MSE (×10⁻³)",
                    "format": "number",
                },
                tooltip=[
                    {"field": "run", "type": "nominal", "label": "Run"},
                    {"field": "probe_count", "type": "quantitative", "label": "Probe trajectories"},
                    {"field": "probe_horizon", "type": "quantitative", "label": "Probe horizon"},
                ],
                layout="full",
                direction="relative",
            )
        )

    used_metrics = {
        "action_sensitivity_ratio",
        "counterfactual_accuracy",
        *(name for name, _ in CONTROL_METRICS),
        *(name for name, _ in TRANSITION_METRICS),
    }
    for name in metric_names:
        if name in used_metrics or name in CONTEXT_METRICS:
            continue
        dataset_id = f"evaluation_{re.sub(r'[^a-zA-Z0-9_]', '_', name)}"
        datasets[dataset_id] = [
            {
                "run": run.label,
                "value": run.metrics[name],
                "seed": run.seed,
                "status": run.status,
            }
            for run in run_results
            if name in run.metrics
        ]
        add_chart(
            _chart(
                f"chart_{dataset_id}",
                f"{_metric_label(name)} across runs",
                "Evaluation values at each run's completed checkpoint.",
                dataset_id,
                "bar",
                {"field": "run", "type": "nominal", "label": "Run"},
                {
                    "field": "value",
                    "type": "quantitative",
                    "label": _metric_label(name),
                    "format": _metric_format(name),
                },
                tooltip=[
                    {"field": "seed", "type": "quantitative", "label": "Seed"},
                    {"field": "status", "type": "nominal", "label": "Status"},
                ],
                orientation="horizontal",
                direction=_metric_direction(name),
            )
        )

    blocks.append(
        {
            "id": "training_heading",
            "type": "markdown",
            "body": (
                "## Selected run training\n\nCurves use deterministic, evenly spaced log rows when a future "
                "dashboard would exceed the bounded snapshot. The raw JSONL remains complete."
            ),
        }
    )
    if primary_objective_rows:
        add_chart(
            _chart(
                "training_primary_objectives",
                "Primary training objectives",
                "The run selector isolates total, action, rollout, and inverse trajectories for one seed.",
                "training_primary_objectives",
                "line",
                {"field": "step", "type": "quantitative", "label": "Optimizer step"},
                {"field": "value", "type": "quantitative", "label": "Objective value", "format": "number"},
                color={"field": "objective", "type": "nominal", "label": "Objective"},
                tooltip=[{"field": "run", "type": "nominal", "label": "Run"}],
                layout="full",
                direction="lower",
            )
        )
    if auxiliary_objective_rows:
        add_chart(
            _chart(
                "training_auxiliary_objectives",
                "Auxiliary training objectives",
                "The run selector isolates counterfactual, regularization, and sampled-chunk trajectories.",
                "training_auxiliary_objectives",
                "line",
                {"field": "step", "type": "quantitative", "label": "Optimizer step"},
                {"field": "value", "type": "quantitative", "label": "Objective value", "format": "number"},
                color={"field": "objective", "type": "nominal", "label": "Objective"},
                tooltip=[{"field": "run", "type": "nominal", "label": "Run"}],
                layout="full",
                direction="lower",
            )
        )
    if accuracy_rows:
        add_chart(
            _chart(
                "training_counterfactual_accuracy",
                "Training counterfactual accuracy",
                "The run selector isolates logged stage-two accuracy and its configured 1/K chance level.",
                "training_accuracy",
                "line",
                {"field": "step", "type": "quantitative", "label": "Optimizer step"},
                {"field": "accuracy", "type": "quantitative", "label": "Accuracy", "format": "percent"},
                color={"field": "series", "type": "nominal", "label": "Series"},
                tooltip=[{"field": "run", "type": "nominal", "label": "Run"}],
                direction="higher",
            )
        )
    if gradient_rows:
        add_chart(
            _chart(
                "training_gradient_norm",
                "Gradient norm",
                "The run selector isolates the pre-clipping norm measured at each logged step.",
                "training_gradient",
                "line",
                {"field": "step", "type": "quantitative", "label": "Optimizer step"},
                {"field": "gradient_norm", "type": "quantitative", "label": "Gradient norm", "format": "number"},
                tooltip=[{"field": "run", "type": "nominal", "label": "Run"}],
                direction="context",
            )
        )
    if curriculum_rows:
        add_chart(
            _chart(
                "training_curriculum",
                "Training curriculum",
                "The run selector isolates logged rollout horizon and sampled delta-t for one seed.",
                "curriculum",
                "line",
                {"field": "step", "type": "quantitative", "label": "Optimizer step"},
                {"field": "value", "type": "quantitative", "label": "Steps", "format": "number"},
                color={"field": "signal", "type": "nominal", "label": "Curriculum signal"},
                tooltip=[{"field": "run", "type": "nominal", "label": "Run"}],
                direction="context",
            )
        )
    if parameter_counts:
        add_chart(
            _chart(
                "parameter_counts",
                "Trainable parameters by component and run",
                "Component parameter counts expose architecture changes that can affect comparisons.",
                "parameter_counts",
                "bar",
                {"field": "component", "type": "nominal", "label": "Component"},
                {"field": "parameters", "type": "quantitative", "label": "Parameters", "format": "compact"},
                color={"field": "run", "type": "nominal", "label": "Run"},
                layout="full",
                group_mode="grouped",
                direction="context",
            )
        )

    tables: list[dict[str, Any]] = [
        {
            "id": "run_inventory",
            "title": "Run inventory and changed controls",
            "subtitle": "Status, hardware, training scope, and the current E1 intervention knobs.",
            "dataset": "run_inventory",
            "sourceId": SOURCE_ID,
            "defaultSort": {"field": "run", "direction": "asc"},
            "density": "dense",
            "layout": "full",
            "columns": [
                {"field": "run", "label": "Run", "type": "text"},
                {"field": "status", "label": "Status", "type": "text"},
                {"field": "device", "label": "Device", "type": "text"},
                {"field": "inverse", "label": "Inverse head", "type": "text"},
                {
                    "field": "counterfactual_weight_display",
                    "label": "CF weight",
                    "type": "text",
                },
                {"field": "kappa_display", "label": "Kappa", "type": "text"},
                {"field": "train_steps", "label": "Train steps", "format": "number"},
                {"field": "probe_count", "label": "Probe count", "format": "number"},
                {"field": "probe_horizon", "label": "Probe horizon", "format": "number"},
                {"field": "source", "label": "Evaluation source", "type": "text"},
            ],
        },
        {
            "id": "result_detail",
            "title": "All final result fields",
            "subtitle": "Evaluation, final-training, parameter, and configured-threshold values for exact lookup.",
            "dataset": "result_detail",
            "sourceId": SOURCE_ID,
            "defaultSort": {"field": "run", "direction": "asc"},
            "density": "dense",
            "layout": "full",
            "columns": [
                {"field": "run", "label": "Run", "type": "text"},
                {"field": "section", "label": "Section", "type": "text"},
                {"field": "metric", "label": "Metric", "type": "text"},
                {"field": "value", "label": "Exact value", "type": "text"},
            ],
        },
    ]
    if training_detail:
        ordered_fields = [
            field
            for field in [
                "run",
                "step",
                "total",
                "action",
                "rollout",
                "inverse",
                "counterfactual",
                "counterfactual_accuracy",
                "reg",
                "chunk",
                "gradient_norm",
                "horizon",
                "delta_t",
            ]
            if field == "run" or field in training_fields
        ]
        ordered_fields.extend(field for field in training_fields if field not in ordered_fields)
        tables.append(
            {
                "id": "training_detail",
                "title": "Selected run training log",
                "subtitle": "Exact logged rows supporting the training curves; sortable and horizontally scrollable.",
                "dataset": "training_detail",
                "sourceId": SOURCE_ID,
                "defaultSort": {"field": "step", "direction": "asc"},
                "density": "dense",
                "layout": "full",
                "columns": [
                    {
                        "field": field,
                        "label": _metric_label(field),
                        **(
                            {"type": "text"}
                            if field == "run"
                            else (
                                {"format": "number"}
                                if field in {"step", "horizon", "delta_t"}
                                else {"type": "text"}
                            )
                        ),
                    }
                    for field in ordered_fields
                ],
            }
        )

    blocks.extend(
        [
            {"id": "inventory", "type": "table", "tableId": "run_inventory", "layout": "full"},
            {"id": "results", "type": "table", "tableId": "result_detail", "layout": "full"},
        ]
    )
    if training_detail:
        blocks.append(
            {"id": "training_rows", "type": "table", "tableId": "training_detail", "layout": "full"}
        )

    thresholds_set = sum(
        value is not None
        for run in run_results
        for value in run.thresholds.values()
        if _is_number(value) or value is None
    )
    development_count = sum(run.status == "development" for run in run_results)
    status_lines = [
        f"- **{development_count} of {len(run_results)} runs are development evidence.** They are diagnostics, "
        "not frozen experiment results.",
        (
            f"- **{thresholds_set} numeric threshold values are configured.**"
            if thresholds_set
            else "- **No numeric pass/fail thresholds are configured in the discovered records.** The dashboard "
            "does not infer a verdict."
        ),
    ]
    status_lines.extend(f"- {notice}" for notice in notices)
    blocks.append(
        {
            "id": "status_notes",
            "type": "markdown",
            "sourceId": SOURCE_ID,
            "body": "## Evidence status\n\n" + "\n".join(status_lines),
        }
    )

    filters: list[dict[str, Any]] = []
    if len(run_results) > 1:
        filter_targets = [
            {"dataset": dataset, "field": "run"}
            for dataset in [
                "action_controls",
                "result_detail",
                "training_primary_objectives",
                "training_auxiliary_objectives",
                "training_accuracy",
                "training_gradient",
                "curriculum",
                "training_detail",
            ]
            if datasets[dataset]
        ]
        filters.append(
            {
                "id": "selected_run",
                "label": "Selected run",
                "dataset": "run_overview",
                "field": "run",
                "defaultValue": latest.label,
                "includeAll": False,
                "targets": filter_targets,
            }
        )

    source = _source(run_results, generated_at)
    return {
        "surface": "dashboard",
        "manifest": {
            "version": 1,
            "surface": "dashboard",
            "title": "PATH-WM Experiment Dashboard",
            "description": "Visual instrument panel over every completed PATH-WM experiment and development run.",
            "generatedAt": generated_at,
            "filters": filters,
            "cards": cards,
            "charts": charts,
            "tables": tables,
            "sources": [{"id": SOURCE_ID, "label": source["label"], "path": SOURCE_QUERY_PATH}],
            "blocks": blocks,
        },
        "snapshot": {
            "version": 1,
            "generatedAt": generated_at,
            "status": "ready",
            "datasets": datasets,
        },
        "sources": [source],
    }


def find_portable_artifact_builder() -> Path:
    """Locate the canonical builder, with an explicit override for non-Codex environments."""

    configured = os.environ.get("PATH_WM_ARTIFACT_BUILDER")
    if configured:
        candidate = Path(configured).expanduser().resolve()
        if candidate.is_file():
            return candidate
        raise DashboardBuildError(f"PATH_WM_ARTIFACT_BUILDER does not name a file: {candidate}")

    cache_root = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "plugins" / "cache"
    candidates = list(
        cache_root.glob(
            "openai-curated-remote/data-analytics/*/skills/build-report/scripts/deliver_portable_artifact.mjs"
        )
    )
    if not candidates:
        raise DashboardBuildError(
            "Data Analytics portable-artifact builder was not found. Set PATH_WM_ARTIFACT_BUILDER "
            "to deliver_portable_artifact.mjs."
        )

    def version_key(path: Path) -> tuple[int, int, int, int]:
        match = re.match(r"(\d+)\.(\d+)\.(\d+)", path.parents[3].name)
        version = tuple(int(part) for part in match.groups()) if match else (0, 0, 0)
        return (*version, path.stat().st_mtime_ns)

    return max(candidates, key=version_key)


def _write_json_atomic(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)


def _deliver_portable_artifact(artifact_path: Path, html_path: Path, builder_path: Path) -> dict[str, Any]:
    node = shutil.which("node")
    if node is None:
        raise DashboardBuildError("Node.js is required to package the self-contained experiment dashboard")
    completed = subprocess.run(
        [node, str(builder_path), "--input", str(artifact_path), "--output", str(html_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or "portable builder failed"
        raise DashboardBuildError(detail)
    try:
        receipt = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise DashboardBuildError("portable builder returned an unreadable verification receipt") from error
    if not receipt.get("ok") or not html_path.is_file():
        raise DashboardBuildError(f"portable builder did not publish {html_path}")
    return receipt


def write_experiment_dashboard(
    runs_root: Path = DEFAULT_RUNS_ROOT,
    artifact_path: Path | None = None,
    html_path: Path | None = None,
    builder_path: Path | None = None,
) -> tuple[Path, Path, dict[str, Any]]:
    """Rebuild the aggregate artifact and verified, self-contained HTML dashboard."""

    runs_root = runs_root.resolve()
    artifact_path = (artifact_path or runs_root / DEFAULT_ARTIFACT.name).resolve()
    html_path = (html_path or runs_root / DEFAULT_HTML.name).resolve()
    run_results, notices = collect_run_results(runs_root)
    artifact = build_dashboard_artifact(run_results, notices)
    _write_json_atomic(artifact_path, artifact)
    receipt = _deliver_portable_artifact(
        artifact_path,
        html_path,
        (builder_path or find_portable_artifact_builder()).resolve(),
    )
    return artifact_path, html_path, receipt


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-root", type=Path, default=DEFAULT_RUNS_ROOT)
    parser.add_argument("--artifact", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--builder", type=Path)
    args = parser.parse_args()
    artifact_path, html_path, receipt = write_experiment_dashboard(
        args.runs_root,
        artifact_path=args.artifact,
        html_path=args.output,
        builder_path=args.builder,
    )
    verification = receipt.get("stages", {}).get("verification", "unknown")
    print(f"Dashboard: {html_path}")
    print(f"Artifact: {artifact_path}")
    print(f"Verification: {verification}")


if __name__ == "__main__":
    main()
